FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y curl default-jdk gcc g++ && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
ENV PYTHONPATH=/app
CMD ["python", "-m", "worker"]
